# Generated by Django 4.2.1 on 2023-05-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ctfpad", "0008_remove_challenge_whiteboard_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="working_on_it",
            field=models.ManyToManyField(
                blank=True, related_name="working_on_challenges", to="ctfpad.member"
            ),
        ),
    ]
