# Generated by Django 4.2.2 on 2023-06-14 12:11

import ctfpad.helpers
import ctfpad.validators
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ctfpad", "0009_challenge_working_on_it"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengefile",
            name="file",
            field=models.FileField(
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/uploads/", location="/code/uploads"
                ),
                upload_to=ctfpad.helpers.get_challenge_upload_path,
                validators=[ctfpad.validators.challenge_file_max_size_validator],
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="avatar",
            field=models.ImageField(
                blank=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/uploads/", location="/code/uploads"
                ),
                upload_to="media/",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="avatar",
            field=models.ImageField(
                blank=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/uploads/", location="/code/uploads"
                ),
                upload_to="media/",
            ),
        ),
    ]
